Implement Snake Game Demo
tsivarev/vk-direct-games-example pull request #1
Opened 2017-12-14 18:50 UTC by erokhinav

2017-12-15 07:12 UTC, tsivarev requested changes

2017-12-15 07:12 UTC, tsivarev commented on app.js
> +const right = "right";
Константы большими буквами определяются

2017-12-15 07:12 UTC, tsivarev commented on app.js
> +const headColor = "#5a76b5";
COLOR_HEAD

2017-12-15 07:12 UTC, tsivarev commented on app.js
> +function handleTouchStart(evt) {
event

2017-12-15 07:12 UTC, tsivarev commented on draw.js
> +        scoreEl.style.fontSize = (scoreSize) + px;
а зачем тут скобки?

2017-12-15 07:12 UTC, tsivarev commented on draw.js
> +        if (snakeX === -1 || snakeY === -1 || snakeX * blockSize === w || snakeY * blockSize === h
(snakeX * blockSize)

2017-12-18 07:11 UTC, tsivarev requested changes

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +        if (type === "head") {
константа.

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +            blockSize / 2 - 1.5, 0, 2 * Math.PI, false);
что такое 1.5?

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +    var w;
Название переменных лучше не сокращать. Так лучше будет читаться

2017-12-18 07:11 UTC, tsivarev commented on app.js
> +const RIGHT = "right";
DIRECTION_RIGHT ?

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +        var scoreEl = document.getElementById("scoreLabel");
scoreElement

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +    var curDirection;
currentDirection

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +        context.lineWidth = 1;
константа. не должно быть magic string/numbers

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +        gameloop = setInterval(drawGame, 180);
180 в константу

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +    var getCurDirection = function () {
getCurrentDirection

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +    var setDirection = function (dir) {
direction

2017-12-18 07:11 UTC, tsivarev commented on app.js
> +const COLOR_HEAD = "#5a76b5";
А зачем эти константы здесь если они используются только в draw.js ?

2017-12-18 07:11 UTC, tsivarev commented on draw.js
> +        updateProperties();
лучше разделить draw.js на два файла: один бизнес логика, второй рендер

2017-12-18 09:32 UTC, erokhinav commented on draw.js
> +            blockSize / 2 - 1.5, 0, 2 * Math.PI, false);
Это уменьшение радиуса на 1.5 единицы координаты в пикселях (если вычесть 1, змейка будет касаться границы поля, если 2 - круги, составляющие змейку, будут находиться слишком далеко друг от друга, а с 1.5 выглядит оптимально).

2017-12-19 06:42 UTC, tsivarev requested changes

2017-12-19 06:42 UTC, tsivarev commented on app.js
> +const HEAD = "head";
Нужно больше осмысленности в названии константа и переменных.

SNAKE_BLOCK_TYPE_HEAD

2017-12-19 06:42 UTC, tsivarev commented on app.js
> +const GAME_INTERVAL = 180;
новую строчку после лучше поставить

2017-12-19 06:42 UTC, tsivarev commented on app.js
> +const LINE_WIDTH = 1;
SNAKE_BLOCK_BORDER_WIDTH

2017-12-21 12:21 UTC, Chaptykov commented on app.js
> +    if (!xDown || !yDown) {
Есть подозрение по коду, что такая обработка событий будет некорректно работать с мультитач-взаимодействием. Имеет смысл где-то в этой функции прерывать жест, если обнаружен мультитач.

```js
if (!!event.touches && event.touches.length > 1) {
  // …
}
```

2017-12-21 12:21 UTC, Chaptykov commented on app.js
> +    xDown = event.touches[0].clientX;
При желании, можно дешево добавить поддержку событий мыши, если везде забирать координаты универсально. Например:

```js
const x = event.clientX || (event.touches && event.touches[0].clientX);
```

2017-12-21 12:21 UTC, Chaptykov commented on style.css
> +    margin-left: -3.45em;
Не очень понятно, зачем здесь использовать `em`. Почему вычисленное значение должно быть именно 104 пикселя?

Если речь идет о выравнивании по центру, то проще либо позиционировать абсолютно при известных размерах:

```css
.startGameButton {
  position: absolute;
  top: 50%;
  left: 50%;
  margin: -50px 0 0 -100px;
}
```

Либо воспользоваться `text-align` на родительском элементе:

```css
.startGameButton {
  display: inline-block;
}
```

В этом случае надо отдельно задуматься о подходе к вертикальному выравниванию.

2017-12-26 10:24 UTC, erokhinav commented on style.css
> +    margin-left: -3.45em;
Если обходиться без `em`, появится лишний пробел слева. Это описано тут: https://goo.gl/SA6LP6.
Похоже, первый способ не подойдет, так как размеры заранее не известны.
К вертикальному выравниванию, пользуясь вторым способом, кажется, должно приводить что-то вроде `margin-top: 50%`, однако на разных устройствах это дает различный эффект (на узких кнопка располагается слишком высоко, а на широких - низко).

2017-12-26 11:31 UTC, tsivarev approved these changes

2017-12-26 11:31 UTC, tsivarev commented on game.js
> +        var length = 3;
я бы сделал константой

2017-12-26 11:31 UTC, merged